services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Password1234!!
      - plugins.security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - os-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - os-net

  logstash:
    image: "public.ecr.aws/opensearchproject/logstash-oss-with-opensearch-output-plugin:8.4.0"
    container_name: logstash
    user: root
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./variant02_linux_syslog_auth.log:/data/variant02_linux_syslog_auth.log:ro
    command: >
      bash -c "
      logstash -f /usr/share/logstash/pipeline/logstash.conf
      "
    depends_on:
      - opensearch
    networks:
      - os-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.0
    container_name: filebeat
    user: root
    command: >
      sh -c "chmod go-w /usr/share/filebeat/filebeat.yml &&
            filebeat -e"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./variant02_linux_syslog_auth.log:/data/variant02_linux_syslog_auth.log:ro
    depends_on:
      - logstash
    networks:
      - os-net

networks:
  os-net:
    driver: bridge
